//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace fastJSON
{
	public class DisplayAttribute : Attribute
	{
		public String Name { get; set; }
		public DisplayAttribute (String name)
		{
			Name = name;
		}
	}
}

