//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class Utils
	{
		public Utils ()
		{
		}

		public static String getDeviceId(){
			AndroidJavaClass up = new AndroidJavaClass ("com.unity3d.player.UnityPlayer");
			AndroidJavaObject currentActivity = up.GetStatic<AndroidJavaObject> ("currentActivity");
			AndroidJavaObject contentResolver = currentActivity.Call<AndroidJavaObject> ("getContentResolver");  
			AndroidJavaClass secure = new AndroidJavaClass ("android.provider.Settings$Secure");
			string android_id = secure.CallStatic<string> ("getString", contentResolver, "android_id");
			return android_id;
		}
	}
}

